version: "3.8"

services:
  apache:
    build:
      context: .
      dockerfile: .docker/php${PHP_VERSION}/DockerFile
    container_name: lamp_8
    mem_limit: 4000m
    mem_reservation: 2000m
    ports:
      - ${APACHE_PORT}:80

    networks:
      public_net:
        ipv4_address: ${MY_IP}.10
    volumes:
      - ${DOCUMENT_ROOT}:/var/www/html
      - ${PHP_INI}/php.ini:/usr/local/etc/php/php.ini
      - ${VHOSTS_DIR}:/etc/apache2/sites-enabled
      - ${APACHE_LOG_DIR}:/var/log/apache2

    depends_on:
      - mysql
    restart: always

  mysql:
    image: mysql:8.0
    ports:
      - 3306:3306
    networks:
      public_net:
        ipv4_address: ${MY_IP}.11
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ${MYSQL_DATA_DIR}:/var/lib/mysql
      # - mysql_data:/var/lib/mysql
    restart: always

# volumes:
#   mysql_data:

networks:
  public_net:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
        - subnet: ${MY_IP}.0/16
